name: Deploy PR Workflow and Config

on:
  workflow_dispatch:
    inputs:
      target_repositories:
        description: "Format: repo1:team1,repo2:team2"
        required: true
      default_team_name:
        description: "Default team name (if not specified per repository)"
        required: false
        default: "Cloud-Platform-Owners"

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: test-env

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Deploy Workflow and Config
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          DEFAULT_TEAM_NAME: ${{ github.event.inputs.default_team_name }}
        run: |
          echo "Starting deployment with token for repositories: ${{ github.event.inputs.target_repositories }}"
          python scripts/deploy_pr_workflow.py "${{ github.event.inputs.target_repositories }}" "${{ env.DEFAULT_TEAM_NAME }}"
